export const demos = [
  { id: "retro", name: "Retro OS", desc: "Windows 95 Style System", color: "#0f766e" },
  { id: "cyberpunk", name: "Cyberpunk", desc: "Neon Hacker Terminal", color: "#00ff00" },
  { id: "3d", name: "3D Void", desc: "Interactive WebGL Particles", color: "#4f46e5" },
  { id: "brutalist", name: "Brutalist", desc: "Raw Data Stream", color: "#fbbf24" },
  { id: "minimal", name: "Swiss Style", desc: "Typography Engine", color: "#ffffff" },
  { id: "neumorphism", name: "Soft UI", desc: "Haptic Interface", color: "#e0e5ec" },
  { id: "pixel", name: "8-Bit World", desc: "Arcade Emulation", color: "#7c3aed" },
  { id: "vaporwave", name: "Vaporwave", desc: "Aesthetic Simulation", color: "#f472b6" },
  { id: "paper", name: "Paper Cut", desc: "Digital Collage Tool", color: "#fcd34d" },
  { id: "ascii", name: "ASCII Cam", desc: "Real-time Text Render", color: "#111827" },
  { id: "corporate", name: "Enterprise", desc: "Synergy Dashboard", color: "#2563eb" },
  { id: "gothic", name: "Gothic", desc: "Tarot Card Reader", color: "#7f1d1d" },
  { id: "sketch", name: "Sketchbook", desc: "Digital Canvas", color: "#f3f4f6" },
  { id: "magazine", name: "Editorial", desc: "Dynamic Layout Engine", color: "#000000" },
  { id: "dashboard", name: "FinTech", desc: "Live Crypto Data", color: "#1e293b" },
  { id: "hud", name: "Sci-Fi HUD", desc: "Target Tracking System", color: "#0891b2" },
  { id: "nature", name: "Organic", desc: "Procedural Fractal Tree", color: "#166534" },
  { id: "glitch", name: "Glitch Art", desc: "Image Corrupter", color: "#701a75" },
  { id: "abstract", name: "Generative", desc: "Node Network Physics", color: "#525252" },
  { id: "bento", name: "Bento Grid", desc: "Modular Profile", color: "#d4d4d8" },
  { id: "physics", name: "Physics Lab", desc: "2D Matter Simulation", color: "#e11d48" },
  { id: "audio", name: "Synth Wave", desc: "Browser Sequencer", color: "#db2777" },
  { id: "globe", name: "Data Globe", desc: "3D Geo-Visualization", color: "#0284c7" },
  { id: "fractal", name: "Mandelbrot", desc: "Infinite Math Explorer", color: "#059669" },
];
